id = "darcula-forest-theme"
name = "Darcula Forest"
version = "0.1.0"
schema_version = 1
authors = ["Oryan"]
description = "Dark green theme based on JetBrains' original Darcula theme"
repository = "https://github.com/oryanm/darcula-forest-zed"
